### ISSUE TITLE
开发者工具，提示version

### ISSUE THREAD

**Issue by 470503790** [czcaiwj/calendar#11]
Cannot read property 'version' of undefined

**Comment by czcaiwj** [comment]
烦请详细描述一下，比如你引入的版本号是多少，日历插件是不存在version这个属性变量的

**Comment by urmyfaith** [comment]
按照readme的使用方法就可以了。

@470503790 .

**Comment by tonyz0129** [comment]
引入版本为1.1.2  
VM7003:1 jsEnginScriptError
Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined

**Comment by czcaiwj** [comment]
你好，请点击开发工具的详情页，先把调试基础库降低，比如1.9.97，可以编译通过，然后再换回你要的版本号。我之前这个错误也重现过，但经过这样的设置后，报错即解除，麻烦尝试一下。

**Comment by czcaiwj** [comment]
微信那边已确认为开发者工具的，下一个版本会升级解决，在升级永久性解决之前，可以按我上一个回答暂时解决。
