### ISSUE TITLE
按照文档配置不显示

### ISSUE THREAD

**Issue by Andy-Sunbin** [czcaiwj/calendar#12]
![image](https://user-images.githubusercontent.com/22465340/40707671-fb38ac62-6423-11e8-8609-5ab23cba34b1.png)
![image](https://user-images.githubusercontent.com/22465340/40707689-0b786446-6424-11e8-8b37-f63d38f5c03b.png)
![image](https://user-images.githubusercontent.com/22465340/40707700-116046d0-6424-11e8-967f-559909510392.png)
![image](https://user-images.githubusercontent.com/22465340/40707734-26cfa4b6-6424-11e8-83e9-70e68942f1ac.png)

不显示不报错,配置如图

**Comment by Andy-Sunbin** [comment]
![Uploading image.png…]()
这是网页的引用

**Comment by czcaiwj** [comment]
你好，估计是微信开发者工具的一个问题，真机预览还是正常的。可以关注我的帖子https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=00060a413a4678ccb1d6eddb45b400&token=1902864696&lang=zh_CN

**Comment by czcaiwj** [comment]
你好，请点击开发工具的详情页，先把调试基础库降低，比如1.9.97，可以编译通过，然后再换回你要的版本号。我之前这个错误也重现过，但经过这样的设置后，报错即解除，麻烦尝试一下。

**Comment by czcaiwj** [comment]
微信那边已确认为开发者工具的，下一个版本会升级解决，在升级永久性解决之前，可以按我上一个回答暂时解决。
