### ISSUE TITLE
版本1.1.2引用报错  

### ISSUE THREAD

**Issue by tonyz0129** [czcaiwj/calendar#14]
引入版本为1.1.2，按照文档操作 报错如下：
VM7003:1 jsEnginScriptError
Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined

**Comment by czcaiwj** [comment]
你好，这是微信开发者工具的一个问题，真机预览还是正常的。可以关注我的帖子https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=00060a413a4678ccb1d6eddb45b400&token=1902864696&lang=zh_CN

**Comment by tonyz0129** [comment]
你好，还是报错  真机 开发者工具都报错

**Comment by czcaiwj** [comment]
你好，请点击开发工具的详情页，先把调试基础库降低，比如1.9.97，可以编译通过，然后再换回你要的版本号。我之前这个错误也重现过，但经过这样的设置后，报错即解除，麻烦尝试一下。

**Comment by czcaiwj** [comment]
微信那边已确认为开发者工具的，下一个版本会升级解决，在升级永久性解决之前，可以按我上一个回答暂时解决。
