### ISSUE TITLE
插件未授权使用，Component is not found in path

### ISSUE THREAD

**Issue by Nnnina** [czcaiwj/calendar#15]
jsEnginScriptError
Component is not found in path "plugin://wx92c68dae5a8bb046/calendar" (using by "pages/index/index")
Error: Component is not found in path "plugin://wx92c68dae5a8bb046/calendar" (using by "pages/index/index")

**Comment by czcaiwj** [comment]
请参考https://github.com/czcaiwj/calendar/wiki/%E6%B7%BB%E5%8A%A0%E6%8F%92%E4%BB%B6%E5%88%B0%E8%87%AA%E5%B7%B1%E7%9A%84%E5%B0%8F%E7%A8%8B%E5%BA%8F

**Comment by czcaiwj** [comment]
你好，这是微信开发者工具的一个问题，真机预览还是正常的。可以关注我的帖子https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=00060a413a4678ccb1d6eddb45b400&token=1902864696&lang=zh_CN

**Comment by czcaiwj** [comment]
尝试下降低下调试基础库
