### ISSUE TITLE
考虑加入滑动切换月份嘛？

### ISSUE THREAD

**Issue by gqbre** [czcaiwj/calendar#2]
RT. <del>有时间的话可以贡献代码</del>
本地已实现，切换月份好像没有提供外部接口？ 我直接操作 month 的值实现。
另外，days-color 的 month 值为何只能设置到前后两个月？感觉直接设置月份的话需求会比较实际一点

**Comment by czcaiwj** [comment]
好主意，可以后期考虑实现。目前切换月份我主要是设计在标题栏的两个按钮那。如果要做滑动切换月份，其实那两个按钮也就没有存在的必要。

days-color 的month可以设置prev、current、next，即上下和当前月。因为考虑到目前日历是单视图，一次只显示一个月，所以没有必要按月份设置。如果按月份设置，那可能还要加入年份。如果是像手机原生日历那种，可以一眼看到近几个月的，那就必须要实现直接设置月份。
