### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by ivhong** [czcaiwj/calendar#20]
您好，我按照文档，在使用的时候报下面的错误，请教是哪里配置错了么？
![image](https://user-images.githubusercontent.com/12603673/41187579-1eeea7de-6bdf-11e8-96d4-ef3b19e55820.png)

**Comment by czcaiwj** [comment]
请先降低项目的调用基础库版本，比如降低到1.9，编译一下，然后再升级到你想要的基础库版本。这是微信开发者工具一个bug，已和微信确认过。

**Comment by ivhong** [comment]
非常感谢！！！
