### ISSUE TITLE
遇到一个点击day，返回的年份错误!

### ISSUE THREAD

**Issue by EasonGaoDevelop** [czcaiwj/calendar#21]
首先设置可以展示上个月和下个月得数据，点击下个月一直到2018年12月份，在里面点击19年1月1号，返回数据 {year: 2018, month: 1, day: 1, color: "#4a4f74", lunarMonth: "冬月", …} ，年份给的是2018

**Comment by czcaiwj** [comment]
稍等 我测试下

**Comment by czcaiwj** [comment]
错误已重现，这个需要升版解决，等微信审核通过后再行通知，谢谢你的反馈！

**Comment by czcaiwj** [comment]
你好，已修复，请引用最新版本1.1.3。
