### ISSUE TITLE
在其他年月时，直接回到当前年月，怎么操作

### ISSUE THREAD

**Issue by ivhong** [czcaiwj/calendar#23]
您好！当日历在其他年月时，直接回到当前年月，怎么操作，或者有没有直接跳转到其他年月的接口？谢谢！

**Comment by czcaiwj** [comment]
你好，并没有，你可以在页面上提供这样功能的按钮，点击后修改日历插件的属性值即可。

**Comment by ivhong** [comment]
多谢，已经解决了， <calendar year="{{year}}" month="{{month}}" /> 这样指定哈？

**Comment by czcaiwj** [comment]
是的
