### ISSUE TITLE
极点日历错误

### ISSUE THREAD

**Issue by liangdaqin** [czcaiwj/calendar#24]
点击日历具体某一天的事件，“lunarDay“和“lunarMonth”的值一样

**Comment by czcaiwj** [comment]
你好，并没有复现你所说的错误，或者请你明确下具体点击哪一天，我这边随机点击是不会出现这个错误的

**Comment by righ7** [comment]
Component is not found in path "pages/calendars/plugin:/wx92c68dae5a8bb046/calendar" (using by "pages/calendars/calendars")这个是什么问题呢

**Comment by czcaiwj** [comment]
你好，麻烦提供插件引入的代码和引用插件页面的代码

**Comment by righ7** [comment]
![image](https://user-images.githubusercontent.com/40221986/41591448-57ac9378-73ec-11e8-88d3-3ba9f48100de.png)
![image](https://user-images.githubusercontent.com/40221986/41591457-5e4479e4-73ec-11e8-9762-b0b2d61f33b4.png)
![image](https://user-images.githubusercontent.com/40221986/41591466-61ef7be8-73ec-11e8-9c3b-cb394cc7cf6d.png)

**Comment by czcaiwj** [comment]
分包远程调试加载自定义组件错误，微信已确认为开发工具bug。请升级至最新版的开发工具，或尝试降低调用基础库，参考链接https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=0004a279fdcbb8d8cec68be7a56c00&highline=Component%20is%20not%20found

**Comment by righ7** [comment]
好的，感谢你的解答

**Comment by WangJunGit** [comment]
农历1994年是错的 还有2020你那也有错误  这个能修复吗
