### ISSUE TITLE
日历主体日期的颜色不支持批量设置颜色?

### ISSUE THREAD

**Issue by songhn** [czcaiwj/calendar#25]
通过board-style="board"属性设置color属性，日期的颜色不会生效，请问如何批量设置日期颜色？不用days_style的方式。

**Comment by czcaiwj** [comment]
日期样式用days-color属性设置

属性名 | 说明
-- | --
month | 要标记的日期所属月份，有效值有prev（上个月）,current（当前月），next（下个月）
day | 要标记的日期
color | 日期文字的颜色，格式为“#HEX”或CSS颜色名
background | 日期单元格的颜色，格式为“#HEX”或CSS颜色名

**Comment by songhn** [comment]
如果设置全月，需要把每一天都进行单独设置？
