### ISSUE TITLE
有没有考虑加上国家节假日？

### ISSUE THREAD

**Issue by Hunterfish** [czcaiwj/calendar#26]
首先非常感谢博主的这个插件，本人后台，对前端了解甚少，也是学习使用！  
也是希望大佬能加上节假日！

**Comment by czcaiwj** [comment]
你好，当初开发这个日历插件，就是为了一次开发免维护的，国家节假日这个，由于每年时间都不一样，要么得设置一个远程服务器来通信获取配置，要么得事先写入插件配置里面，对插件本身的开发都不实际。

相反的，有空的时候，我会考虑把农历这个设置为配置项，既可以使用插件本身提供的农历，也可以配置为使用者自行配置的文本，这样不仅解决了节假日问题，还可以解决类似上班，补休，以及其他自定义字段的内容。
