### ISSUE TITLE
如何实现点击日期改变背景颜色

### ISSUE THREAD

**Issue by alexxd35** [czcaiwj/calendar#27]
如何可以实现点击日期改变被点击的日期的背景颜色

**Comment by czcaiwj** [comment]
1、监听dayClick事件，获取点击日期
2、判断是否是目标日期
3、修改days-color数组

**Comment by alexxd35** [comment]
现在可以了，如果需要多选的话，需要怎样做呢？谢谢你！

**Comment by alexxd35** [comment]
我想可以点选日期然后变色，然后可以把选择的日期数据下来

**Comment by alexxd35** [comment]
洗澡，足浴，按摩院，大保健，兄弟挺有意思

**Comment by alexxd35** [comment]
可以了

**Comment by alexxd35** [comment]
还有一个问题，month那里，我要跨月选择，不能用current那应该用什么？我用event.detail.month 不行

**Comment by alexxd35** [comment]
@czcaiwj @Hunterfish

**Comment by Hunterfish** [comment]
我也在研究，因为切换上下月后，没有保存，所以显示失效了。
切换时放到list里呢，博主有更好地建议吗
![issue1](https://user-images.githubusercontent.com/25543945/41724566-65214070-75a0-11e8-8c69-98f55d766e85.gif)

**Comment by jacena** [comment]
能不能在日期底下显示添加的事件名称。样式区分下工作日和周末，还有当日的默认显示样式

**Comment by alexxd35** [comment]
@Hunterfish 为什么例如我6月份选择了5号，然后切换到7月，那个5号还是亮着的

**Comment by alexxd35** [comment]
month:'current' 究竟怎么改啊，我改成月份不行啊，一定要用'current'才行吗

**Comment by czcaiwj** [comment]
切换月份的话，要保持上下月之前选择的东西，那肯定是自己代码实现逻辑的问题，你可以在js代码里面实现一个数组，做持久化保存。然后监听月份切换时间，在月份切换时间中检测切换到的月份是否在持久化数组里面，有就设置对应的样式就好了。

**Comment by alexxd35** [comment]
我的测试days_style的数组设置了 month:6  这样，不能改变样式，但是month:'current' 这样就可以，请问是什么原理啊

**Comment by alexxd35** [comment]
ds.push({
          month: event.detail.month, day: event.detail.day, color: 'white', background: '#0BC4A1'
        });
为啥这样不能改变样式
 ds.push({
          month: 'current', day: event.detail.day, color: 'white', background: '#0BC4A1'
        });
这样又可以啊

**Comment by xihaa** [comment]
请问js中怎么改变days-color数组啊？

**Comment by alexxd35** [comment]
@czcaiwj 月份怎么记录啊，都是current啊

**Comment by ghost** [comment]
我点击事件颜色在ios真机显示没问题，在安卓上测试时就显示不了颜色，有遇到相同问题的么？
