### ISSUE TITLE
能不能在日期底下显示添加的事件名称。样式区分下工作日和周末，还有当日的默认显示样式

### ISSUE THREAD

**Issue by jacena** [czcaiwj/calendar#28]
能不能在日期底下显示添加的事件名称。样式区分下工作日和周末，还有当日的默认显示样式

**Comment by czcaiwj** [comment]
1、样式的都是可以自己自定义的啊
2、不太明白日期底下显示添加的事情名称这个具体指什么，把农历的改成自定义文本吗？如果是的话，目前正在开发中

**Comment by fioname3** [comment]
作者大大好，请问“把农历文本改成自定义文本”这个功能开发完了吗
