### ISSUE TITLE
未来会增加1900年以前的吗？万年历

### ISSUE THREAD

**Issue by jymusic0663** [czcaiwj/calendar#3]
如题，看到说明只能1900~2099年，所以有此疑问

**Comment by czcaiwj** [comment]
你好，农历有以下特点：
1、农历分大小月，大月30天，小月29天，但一年中哪个月为大月，哪个月为小月，是无规律的。
2、农历每十年有4个闰年，但哪一年为闰年也是不确定的。
3、而闰月中，哪个闰月为大月，哪个为小月也是不确定的。

你可以参考“calendar/插件开发代码/plugin/components/calendar/lunar.js”这个文件，里面有对应的农历算法。
因为这些所谓的农历数据，是需要天文台测定的，如果天文台没给出之前的或之后的，理论上是无法扩展的。
你可以随便下载几款手机APP或电脑的系统日历，相信90%以上的都是在我这个插件目前支持的范围内。其实我这个插件是支持1900到2100年的，但为了避免日期越界，所以代码里写死了只到2099年。

**Comment by jymusic0663** [comment]
好的，多谢多谢
