### ISSUE TITLE
能否增加左右滑动切换上个月和下个月？

### ISSUE THREAD

**Issue by TonyLiuYan** [czcaiwj/calendar#31]
目前插件切换上个月和下个月的按钮触碰范围比较小，有的时候手指点击无法点击上触发事件区域，能否增加左右滑动来切换上个月和下个月，或者增大触碰区域，多谢！

**Comment by czcaiwj** [comment]
你好，关于“目前插件切换上个月和下个月的按钮触碰范围比较小”，这个你可以通过属性隐藏掉上下月按钮，然后自己在页面上花2个大一点的。

至于“能否增加左右滑动来切换上个月和下个月，或者增大触碰区域”这个有考虑过，但优先级不高，有空再试试做上去。非常感谢你的关注，谢谢！
